---
- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: devstack is not defined or not devstack

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  when: devstack is not defined or not devstack
