- name: Download edX Prospectus Service nginx redirects file
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'prospectus'
    PROSPECTUS_DATA_DIR: "/edx/var/prospectus"
    NGINX_OVERRIDE_DEFAULT_MAP_HASH_SIZE: True
    NGINX_MAP_HASH_MAX_SIZE: 4096
    NGINX_MAP_HASH_BUCKET_SIZE: 128
    PROSPECTUS_ENABLED: True
    PROSPECTUS_SANDBOX_BUILD: FALSE
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
  tasks:
    - name: Create redirects config directory
      tags:
        - download_prospectus_redirects
      file:
        path: "{{ prospectus_redirect_file | dirname }}"
        state: directory
###JDM###    - name: Download prospectus redirects from S3
###JDM###      tags:
###JDM###        - download_prospectus_redirects
###JDM###      aws_s3:
###JDM###        bucket: "{{ PROSPECTUS_REDIRECT_CONFIG_S3_BUCKET }}"
###JDM###        object: "prospectus-redirects/{{ PROSPECTUS_S3_HOSTING_PREFIX }}/{{ PROSPECTUS_ENVIRONMENT }}-{{ prospectus_redirect_file | basename }}"
###JDM###        dest: "{{ prospectus_redirect_file }}"
###JDM###        mode: get
    - name: Upload prospectus redirects from GoCD
      when: PROSPECTUS_S3_HOSTING_ENABLED|bool
      copy:
        src: "{{ artifact_path }}/prospectus-redirects.conf"
        dest: "{{ prospectus_redirect_file }}"
