- name: Download edX Prospectus Service nginx redirects file
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'prospectus'
    PROSPECTUS_DATA_DIR: "/edx/var/prospectus"
    NGINX_OVERRIDE_DEFAULT_MAP_HASH_SIZE: True
    NGINX_MAP_HASH_MAX_SIZE: 4096
    NGINX_MAP_HASH_BUCKET_SIZE: 128
    PROSPECTUS_ENABLED: True
    PROSPECTUS_SANDBOX_BUILD: FALSE
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
  tasks:
    - name: Create redirects config directory
      tags:
        - download_prospectus_redirects
      file:
        path: "{{ prospectus_redirect_file | dirname }}"
        state: directory
    - name: Download prospectus redirects from S3
      tags:
        - download_prospectus_redirects
      aws_s3:
        bucket: "{{ PROSPECTUS_REDIRECT_CONFIG_S3_BUCKET }}"
        object: "prospectus-redirects/{{ PROSPECTUS_UPLOAD_TO_S3_PREFIX }}/{{ PROSPECTUS_ENVIRONMENT }}-{{ prospectus_redirect_file | basename }}"
        dest: "{{ prospectus_redirect_file }}"
        mode: get
