name: Playbook Test

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Run test docker build
      run: |
        timeout 90m make --keep-going docker.build.credentials
        docker run -t edxops/credentials:latest atlas --help
